ValerioTest.Web/Pages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ValerioTest.Data;
using ValerioTest.Models;

namespace ValerioTest.Web
{


    [Authorize]
    public class EditModel : PageModel
    {

        private readonly ImodelliRep _modelliRepository;

        [BindProperty]
        public Modelli Modell { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        public EditModel(ImodelliRep modelliRepository)
        {
            _modelliRepository = modelliRepository;
        }

        public IActionResult OnGet(int id)
        {
            Modell = _modelliRepository.GetById(id);
            if (Modell == null)
                return NotFound();

            return Page();
        }

        public IActionResult OnPost(int id)
        {
          

            if (ModelState.IsValid)
            {
                var modelli = _modelliRepository.GetById(id);
                modelli.Aula = Modell.Aula;
                return RedirectToPage("/Index");
            }

            return Page();
        }
/*
        public IActionResult OnPostDeleteProduct(int id)
        {
            try
            {
                _modelliRepository.Delete(id);
               //  return RedirectToPage("/Products/Index"); 
            }
            catch (Exception)
            {
                ErrorMessage = "Non è possibile cancellare il prodotto in quanto già utilizzato.";
                //return RedirectToPage("/Products/Edit", new { id });
            }  

        }*/

    }
}

ValerioTest.Web/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ValerioTest.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ValerioTest.Web/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using ValerioTest.Data;
using ValerioTest.Models;

namespace ValerioTest.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ImodelliRep _modelliRepository;

        public IEnumerable<Modelli> Modells { get; set; }

        public IndexModel(ImodelliRep modelliRepository)
        {
            _modelliRepository = modelliRepository;
        }

        public void OnGet()
        {
            Modells = _modelliRepository.GetAll();
        }
    }
}

ValerioTest.Web/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ValerioTest.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ValerioTest.Web/Pages/Shared/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ValerioTest.Web
{
    public class DetailModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

ValerioTest.Web/Pages/Edit.cshtml
@page
@model ValerioTest.Web.EditModel
@{
    ViewData["Title"] = "Edit";
}

<h1>Modifica del prodotto @Model.Modell.Aula</h1>


@if(!string.IsNullOrWhiteSpace(Model.ErrorMessage))
{
    <div role="alert" class="alert alert-danger">
        @Model.ErrorMessage
    </div>
}


<form method="post">
    <div class="text-danger" asp-validation-summary="All"></div>

    <input asp-for="Modell.IdPiano" type="hidden" />

    <div class="form-group">
        <label asp-for="Modell.Aula"></label>
        <input asp-for="Modell.Aula" class="form-control" />
        <span asp-validation-for="Modell.Aula" class="text-danger" />
    </div>



    <button type="submit" class="btn btn-success">Salva</button>
    <a class="btn btn-secondary" asp-page="/Products/Index">Annulla</a>
</form>

<hr />


<form method="post" asp-page-handler="DeleteProduct">
    <button class="btn btn-danger" type="submit">Elimina</button>

</form>




@section Scripts { 

    <partial name="_ValidationScriptsPartial" />
}

ValerioTest.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-3">Esame di Stato</h1>
    <h3 class="display-4">Corso IoT</h3>
</div>
<p></p>
<p></p>
<p></p>
<br />
<div class="row">
    @foreach (var p in Model.Modells)      // ----VISUALIZZO  gli oggetti nella tabella -->
    {
        <div class="col-4">
            <div class="card mb-2 ">
                <div class="card-body">
                    <!--visualizzaione tabella database-->

                    <h5 class="card-title">Piano: @p.IdPiano</h5>

                    Aula:          @p.Aula<br />

                    Nome:        @p.Nome<br />
                    Materia: @p.Materia<br />
                    Scadenza: @p.Scadenza<br />

                </div>
            </div>
        </div>
    }
    
    
</div>

ValerioTest.Web/Pages/Shared/Detail.cshtml
@page
@model ValerioTest.Web.DetailModel
@{
    ViewData["Title"] = "Detail";
}

<h1>Detail</h1>

ValerioTest.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Esame di stato IoT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Valerio Anzilotti</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ValerioTest.Web - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>